server:
  port: 18090
  servlet:
    context-path: /
  error:
    include-stacktrace: never

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      # deals with single and multi-valued JWT claims
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://issuer.zitadel.ch
          jwk-set-uri: https://api.zitadel.ch/oauth/v2/keys
        opaquetoken:
          introspection-uri: https://api.zitadel.ch/oauth/v2/introspect
          client-id: ...api-client-id
          client-secret: ...api-client-secret
